// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employees.proto

package org.demo.protobuf;

public interface DepartmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Department)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Employee employees = 1;</code>
   */
  java.util.List<org.demo.protobuf.Employee> 
      getEmployeesList();
  /**
   * <code>repeated .Employee employees = 1;</code>
   */
  org.demo.protobuf.Employee getEmployees(int index);
  /**
   * <code>repeated .Employee employees = 1;</code>
   */
  int getEmployeesCount();
  /**
   * <code>repeated .Employee employees = 1;</code>
   */
  java.util.List<? extends org.demo.protobuf.EmployeeOrBuilder> 
      getEmployeesOrBuilderList();
  /**
   * <code>repeated .Employee employees = 1;</code>
   */
  org.demo.protobuf.EmployeeOrBuilder getEmployeesOrBuilder(
      int index);
}
