// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employees.proto

package org.demo.protobuf;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .Employee.PhoneNumber phones = 4;</code>
   */
  java.util.List<org.demo.protobuf.Employee.PhoneNumber> 
      getPhonesList();
  /**
   * <code>repeated .Employee.PhoneNumber phones = 4;</code>
   */
  org.demo.protobuf.Employee.PhoneNumber getPhones(int index);
  /**
   * <code>repeated .Employee.PhoneNumber phones = 4;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .Employee.PhoneNumber phones = 4;</code>
   */
  java.util.List<? extends org.demo.protobuf.Employee.PhoneNumberOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .Employee.PhoneNumber phones = 4;</code>
   */
  org.demo.protobuf.Employee.PhoneNumberOrBuilder getPhonesOrBuilder(
      int index);
}
