// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aggregate.proto

package com.netapp.asup.serde.common.proto;

public final class AggregateOuterClass {
  private AggregateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AggregateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Aggregate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string object_name = 1;</code>
     * @return The objectName.
     */
    java.lang.String getObjectName();
    /**
     * <code>string object_name = 1;</code>
     * @return The bytes for objectName.
     */
    com.google.protobuf.ByteString
        getObjectNameBytes();

    /**
     * <code>int64 prev_timestamp = 2;</code>
     * @return The prevTimestamp.
     */
    long getPrevTimestamp();

    /**
     * <code>int64 current_timestamp = 3;</code>
     * @return The currentTimestamp.
     */
    long getCurrentTimestamp();

    /**
     * <code>string instance_name = 4;</code>
     * @return The instanceName.
     */
    java.lang.String getInstanceName();
    /**
     * <code>string instance_name = 4;</code>
     * @return The bytes for instanceName.
     */
    com.google.protobuf.ByteString
        getInstanceNameBytes();

    /**
     * <code>repeated .Counter counters = 5;</code>
     */
    java.util.List<com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter> 
        getCountersList();
    /**
     * <code>repeated .Counter counters = 5;</code>
     */
    com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter getCounters(int index);
    /**
     * <code>repeated .Counter counters = 5;</code>
     */
    int getCountersCount();
    /**
     * <code>repeated .Counter counters = 5;</code>
     */
    java.util.List<? extends com.netapp.asup.serde.common.proto.AggregateOuterClass.CounterOrBuilder> 
        getCountersOrBuilderList();
    /**
     * <code>repeated .Counter counters = 5;</code>
     */
    com.netapp.asup.serde.common.proto.AggregateOuterClass.CounterOrBuilder getCountersOrBuilder(
        int index);
  }
  /**
   * <pre>
   * Field sequence from 1 to 15 takes 1 byte and from 16 through 2047 takes two bytes, so more frequently message
   * elements should be used here. And non frequent ones should be used latter.
   * </pre>
   *
   * Protobuf type {@code Aggregate}
   */
  public static final class Aggregate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Aggregate)
      AggregateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Aggregate.newBuilder() to construct.
    private Aggregate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Aggregate() {
      objectName_ = "";
      instanceName_ = "";
      counters_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Aggregate();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Aggregate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              objectName_ = s;
              break;
            }
            case 16: {

              prevTimestamp_ = input.readInt64();
              break;
            }
            case 24: {

              currentTimestamp_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              instanceName_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                counters_ = new java.util.ArrayList<com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter>();
                mutable_bitField0_ |= 0x00000001;
              }
              counters_.add(
                  input.readMessage(com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          counters_ = java.util.Collections.unmodifiableList(counters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netapp.asup.serde.common.proto.AggregateOuterClass.internal_static_Aggregate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netapp.asup.serde.common.proto.AggregateOuterClass.internal_static_Aggregate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate.class, com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate.Builder.class);
    }

    public static final int OBJECT_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object objectName_;
    /**
     * <code>string object_name = 1;</code>
     * @return The objectName.
     */
    @java.lang.Override
    public java.lang.String getObjectName() {
      java.lang.Object ref = objectName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectName_ = s;
        return s;
      }
    }
    /**
     * <code>string object_name = 1;</code>
     * @return The bytes for objectName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getObjectNameBytes() {
      java.lang.Object ref = objectName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREV_TIMESTAMP_FIELD_NUMBER = 2;
    private long prevTimestamp_;
    /**
     * <code>int64 prev_timestamp = 2;</code>
     * @return The prevTimestamp.
     */
    @java.lang.Override
    public long getPrevTimestamp() {
      return prevTimestamp_;
    }

    public static final int CURRENT_TIMESTAMP_FIELD_NUMBER = 3;
    private long currentTimestamp_;
    /**
     * <code>int64 current_timestamp = 3;</code>
     * @return The currentTimestamp.
     */
    @java.lang.Override
    public long getCurrentTimestamp() {
      return currentTimestamp_;
    }

    public static final int INSTANCE_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object instanceName_;
    /**
     * <code>string instance_name = 4;</code>
     * @return The instanceName.
     */
    @java.lang.Override
    public java.lang.String getInstanceName() {
      java.lang.Object ref = instanceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instanceName_ = s;
        return s;
      }
    }
    /**
     * <code>string instance_name = 4;</code>
     * @return The bytes for instanceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInstanceNameBytes() {
      java.lang.Object ref = instanceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instanceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTERS_FIELD_NUMBER = 5;
    private java.util.List<com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter> counters_;
    /**
     * <code>repeated .Counter counters = 5;</code>
     */
    @java.lang.Override
    public java.util.List<com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter> getCountersList() {
      return counters_;
    }
    /**
     * <code>repeated .Counter counters = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.netapp.asup.serde.common.proto.AggregateOuterClass.CounterOrBuilder> 
        getCountersOrBuilderList() {
      return counters_;
    }
    /**
     * <code>repeated .Counter counters = 5;</code>
     */
    @java.lang.Override
    public int getCountersCount() {
      return counters_.size();
    }
    /**
     * <code>repeated .Counter counters = 5;</code>
     */
    @java.lang.Override
    public com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter getCounters(int index) {
      return counters_.get(index);
    }
    /**
     * <code>repeated .Counter counters = 5;</code>
     */
    @java.lang.Override
    public com.netapp.asup.serde.common.proto.AggregateOuterClass.CounterOrBuilder getCountersOrBuilder(
        int index) {
      return counters_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objectName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, objectName_);
      }
      if (prevTimestamp_ != 0L) {
        output.writeInt64(2, prevTimestamp_);
      }
      if (currentTimestamp_ != 0L) {
        output.writeInt64(3, currentTimestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instanceName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, instanceName_);
      }
      for (int i = 0; i < counters_.size(); i++) {
        output.writeMessage(5, counters_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objectName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, objectName_);
      }
      if (prevTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, prevTimestamp_);
      }
      if (currentTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, currentTimestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instanceName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, instanceName_);
      }
      for (int i = 0; i < counters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, counters_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate)) {
        return super.equals(obj);
      }
      com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate other = (com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate) obj;

      if (!getObjectName()
          .equals(other.getObjectName())) return false;
      if (getPrevTimestamp()
          != other.getPrevTimestamp()) return false;
      if (getCurrentTimestamp()
          != other.getCurrentTimestamp()) return false;
      if (!getInstanceName()
          .equals(other.getInstanceName())) return false;
      if (!getCountersList()
          .equals(other.getCountersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OBJECT_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getObjectName().hashCode();
      hash = (37 * hash) + PREV_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPrevTimestamp());
      hash = (37 * hash) + CURRENT_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCurrentTimestamp());
      hash = (37 * hash) + INSTANCE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getInstanceName().hashCode();
      if (getCountersCount() > 0) {
        hash = (37 * hash) + COUNTERS_FIELD_NUMBER;
        hash = (53 * hash) + getCountersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Field sequence from 1 to 15 takes 1 byte and from 16 through 2047 takes two bytes, so more frequently message
     * elements should be used here. And non frequent ones should be used latter.
     * </pre>
     *
     * Protobuf type {@code Aggregate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Aggregate)
        com.netapp.asup.serde.common.proto.AggregateOuterClass.AggregateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netapp.asup.serde.common.proto.AggregateOuterClass.internal_static_Aggregate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netapp.asup.serde.common.proto.AggregateOuterClass.internal_static_Aggregate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate.class, com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate.Builder.class);
      }

      // Construct using com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCountersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        objectName_ = "";

        prevTimestamp_ = 0L;

        currentTimestamp_ = 0L;

        instanceName_ = "";

        if (countersBuilder_ == null) {
          counters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          countersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netapp.asup.serde.common.proto.AggregateOuterClass.internal_static_Aggregate_descriptor;
      }

      @java.lang.Override
      public com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate getDefaultInstanceForType() {
        return com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate.getDefaultInstance();
      }

      @java.lang.Override
      public com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate build() {
        com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate buildPartial() {
        com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate result = new com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate(this);
        int from_bitField0_ = bitField0_;
        result.objectName_ = objectName_;
        result.prevTimestamp_ = prevTimestamp_;
        result.currentTimestamp_ = currentTimestamp_;
        result.instanceName_ = instanceName_;
        if (countersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            counters_ = java.util.Collections.unmodifiableList(counters_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.counters_ = counters_;
        } else {
          result.counters_ = countersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate) {
          return mergeFrom((com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate other) {
        if (other == com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate.getDefaultInstance()) return this;
        if (!other.getObjectName().isEmpty()) {
          objectName_ = other.objectName_;
          onChanged();
        }
        if (other.getPrevTimestamp() != 0L) {
          setPrevTimestamp(other.getPrevTimestamp());
        }
        if (other.getCurrentTimestamp() != 0L) {
          setCurrentTimestamp(other.getCurrentTimestamp());
        }
        if (!other.getInstanceName().isEmpty()) {
          instanceName_ = other.instanceName_;
          onChanged();
        }
        if (countersBuilder_ == null) {
          if (!other.counters_.isEmpty()) {
            if (counters_.isEmpty()) {
              counters_ = other.counters_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCountersIsMutable();
              counters_.addAll(other.counters_);
            }
            onChanged();
          }
        } else {
          if (!other.counters_.isEmpty()) {
            if (countersBuilder_.isEmpty()) {
              countersBuilder_.dispose();
              countersBuilder_ = null;
              counters_ = other.counters_;
              bitField0_ = (bitField0_ & ~0x00000001);
              countersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCountersFieldBuilder() : null;
            } else {
              countersBuilder_.addAllMessages(other.counters_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object objectName_ = "";
      /**
       * <code>string object_name = 1;</code>
       * @return The objectName.
       */
      public java.lang.String getObjectName() {
        java.lang.Object ref = objectName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          objectName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string object_name = 1;</code>
       * @return The bytes for objectName.
       */
      public com.google.protobuf.ByteString
          getObjectNameBytes() {
        java.lang.Object ref = objectName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          objectName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string object_name = 1;</code>
       * @param value The objectName to set.
       * @return This builder for chaining.
       */
      public Builder setObjectName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        objectName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string object_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearObjectName() {
        
        objectName_ = getDefaultInstance().getObjectName();
        onChanged();
        return this;
      }
      /**
       * <code>string object_name = 1;</code>
       * @param value The bytes for objectName to set.
       * @return This builder for chaining.
       */
      public Builder setObjectNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        objectName_ = value;
        onChanged();
        return this;
      }

      private long prevTimestamp_ ;
      /**
       * <code>int64 prev_timestamp = 2;</code>
       * @return The prevTimestamp.
       */
      @java.lang.Override
      public long getPrevTimestamp() {
        return prevTimestamp_;
      }
      /**
       * <code>int64 prev_timestamp = 2;</code>
       * @param value The prevTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setPrevTimestamp(long value) {
        
        prevTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 prev_timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrevTimestamp() {
        
        prevTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private long currentTimestamp_ ;
      /**
       * <code>int64 current_timestamp = 3;</code>
       * @return The currentTimestamp.
       */
      @java.lang.Override
      public long getCurrentTimestamp() {
        return currentTimestamp_;
      }
      /**
       * <code>int64 current_timestamp = 3;</code>
       * @param value The currentTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentTimestamp(long value) {
        
        currentTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 current_timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentTimestamp() {
        
        currentTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object instanceName_ = "";
      /**
       * <code>string instance_name = 4;</code>
       * @return The instanceName.
       */
      public java.lang.String getInstanceName() {
        java.lang.Object ref = instanceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          instanceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string instance_name = 4;</code>
       * @return The bytes for instanceName.
       */
      public com.google.protobuf.ByteString
          getInstanceNameBytes() {
        java.lang.Object ref = instanceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instanceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string instance_name = 4;</code>
       * @param value The instanceName to set.
       * @return This builder for chaining.
       */
      public Builder setInstanceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        instanceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string instance_name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstanceName() {
        
        instanceName_ = getDefaultInstance().getInstanceName();
        onChanged();
        return this;
      }
      /**
       * <code>string instance_name = 4;</code>
       * @param value The bytes for instanceName to set.
       * @return This builder for chaining.
       */
      public Builder setInstanceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        instanceName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter> counters_ =
        java.util.Collections.emptyList();
      private void ensureCountersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          counters_ = new java.util.ArrayList<com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter>(counters_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter, com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.Builder, com.netapp.asup.serde.common.proto.AggregateOuterClass.CounterOrBuilder> countersBuilder_;

      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public java.util.List<com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter> getCountersList() {
        if (countersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(counters_);
        } else {
          return countersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public int getCountersCount() {
        if (countersBuilder_ == null) {
          return counters_.size();
        } else {
          return countersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter getCounters(int index) {
        if (countersBuilder_ == null) {
          return counters_.get(index);
        } else {
          return countersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public Builder setCounters(
          int index, com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter value) {
        if (countersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCountersIsMutable();
          counters_.set(index, value);
          onChanged();
        } else {
          countersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public Builder setCounters(
          int index, com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.Builder builderForValue) {
        if (countersBuilder_ == null) {
          ensureCountersIsMutable();
          counters_.set(index, builderForValue.build());
          onChanged();
        } else {
          countersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public Builder addCounters(com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter value) {
        if (countersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCountersIsMutable();
          counters_.add(value);
          onChanged();
        } else {
          countersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public Builder addCounters(
          int index, com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter value) {
        if (countersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCountersIsMutable();
          counters_.add(index, value);
          onChanged();
        } else {
          countersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public Builder addCounters(
          com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.Builder builderForValue) {
        if (countersBuilder_ == null) {
          ensureCountersIsMutable();
          counters_.add(builderForValue.build());
          onChanged();
        } else {
          countersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public Builder addCounters(
          int index, com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.Builder builderForValue) {
        if (countersBuilder_ == null) {
          ensureCountersIsMutable();
          counters_.add(index, builderForValue.build());
          onChanged();
        } else {
          countersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public Builder addAllCounters(
          java.lang.Iterable<? extends com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter> values) {
        if (countersBuilder_ == null) {
          ensureCountersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, counters_);
          onChanged();
        } else {
          countersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public Builder clearCounters() {
        if (countersBuilder_ == null) {
          counters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          countersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public Builder removeCounters(int index) {
        if (countersBuilder_ == null) {
          ensureCountersIsMutable();
          counters_.remove(index);
          onChanged();
        } else {
          countersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.Builder getCountersBuilder(
          int index) {
        return getCountersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public com.netapp.asup.serde.common.proto.AggregateOuterClass.CounterOrBuilder getCountersOrBuilder(
          int index) {
        if (countersBuilder_ == null) {
          return counters_.get(index);  } else {
          return countersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public java.util.List<? extends com.netapp.asup.serde.common.proto.AggregateOuterClass.CounterOrBuilder> 
           getCountersOrBuilderList() {
        if (countersBuilder_ != null) {
          return countersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(counters_);
        }
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.Builder addCountersBuilder() {
        return getCountersFieldBuilder().addBuilder(
            com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.getDefaultInstance());
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.Builder addCountersBuilder(
          int index) {
        return getCountersFieldBuilder().addBuilder(
            index, com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.getDefaultInstance());
      }
      /**
       * <code>repeated .Counter counters = 5;</code>
       */
      public java.util.List<com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.Builder> 
           getCountersBuilderList() {
        return getCountersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter, com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.Builder, com.netapp.asup.serde.common.proto.AggregateOuterClass.CounterOrBuilder> 
          getCountersFieldBuilder() {
        if (countersBuilder_ == null) {
          countersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter, com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.Builder, com.netapp.asup.serde.common.proto.AggregateOuterClass.CounterOrBuilder>(
                  counters_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          counters_ = null;
        }
        return countersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Aggregate)
    }

    // @@protoc_insertion_point(class_scope:Aggregate)
    private static final com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate();
    }

    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Aggregate>
        PARSER = new com.google.protobuf.AbstractParser<Aggregate>() {
      @java.lang.Override
      public Aggregate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Aggregate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Aggregate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Aggregate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.netapp.asup.serde.common.proto.AggregateOuterClass.Aggregate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CounterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Counter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string counter_name = 1;</code>
     * @return The counterName.
     */
    java.lang.String getCounterName();
    /**
     * <code>string counter_name = 1;</code>
     * @return The bytes for counterName.
     */
    com.google.protobuf.ByteString
        getCounterNameBytes();

    /**
     * <code>int64 prev_value = 2;</code>
     * @return The prevValue.
     */
    long getPrevValue();

    /**
     * <code>int64 current_value = 3;</code>
     * @return The currentValue.
     */
    long getCurrentValue();
  }
  /**
   * Protobuf type {@code Counter}
   */
  public static final class Counter extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Counter)
      CounterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Counter.newBuilder() to construct.
    private Counter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Counter() {
      counterName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Counter();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Counter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              counterName_ = s;
              break;
            }
            case 16: {

              prevValue_ = input.readInt64();
              break;
            }
            case 24: {

              currentValue_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netapp.asup.serde.common.proto.AggregateOuterClass.internal_static_Counter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netapp.asup.serde.common.proto.AggregateOuterClass.internal_static_Counter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.class, com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.Builder.class);
    }

    public static final int COUNTER_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object counterName_;
    /**
     * <code>string counter_name = 1;</code>
     * @return The counterName.
     */
    @java.lang.Override
    public java.lang.String getCounterName() {
      java.lang.Object ref = counterName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        counterName_ = s;
        return s;
      }
    }
    /**
     * <code>string counter_name = 1;</code>
     * @return The bytes for counterName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCounterNameBytes() {
      java.lang.Object ref = counterName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        counterName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREV_VALUE_FIELD_NUMBER = 2;
    private long prevValue_;
    /**
     * <code>int64 prev_value = 2;</code>
     * @return The prevValue.
     */
    @java.lang.Override
    public long getPrevValue() {
      return prevValue_;
    }

    public static final int CURRENT_VALUE_FIELD_NUMBER = 3;
    private long currentValue_;
    /**
     * <code>int64 current_value = 3;</code>
     * @return The currentValue.
     */
    @java.lang.Override
    public long getCurrentValue() {
      return currentValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(counterName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, counterName_);
      }
      if (prevValue_ != 0L) {
        output.writeInt64(2, prevValue_);
      }
      if (currentValue_ != 0L) {
        output.writeInt64(3, currentValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(counterName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, counterName_);
      }
      if (prevValue_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, prevValue_);
      }
      if (currentValue_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, currentValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter)) {
        return super.equals(obj);
      }
      com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter other = (com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter) obj;

      if (!getCounterName()
          .equals(other.getCounterName())) return false;
      if (getPrevValue()
          != other.getPrevValue()) return false;
      if (getCurrentValue()
          != other.getCurrentValue()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COUNTER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getCounterName().hashCode();
      hash = (37 * hash) + PREV_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPrevValue());
      hash = (37 * hash) + CURRENT_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCurrentValue());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Counter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Counter)
        com.netapp.asup.serde.common.proto.AggregateOuterClass.CounterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netapp.asup.serde.common.proto.AggregateOuterClass.internal_static_Counter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netapp.asup.serde.common.proto.AggregateOuterClass.internal_static_Counter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.class, com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.Builder.class);
      }

      // Construct using com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        counterName_ = "";

        prevValue_ = 0L;

        currentValue_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netapp.asup.serde.common.proto.AggregateOuterClass.internal_static_Counter_descriptor;
      }

      @java.lang.Override
      public com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter getDefaultInstanceForType() {
        return com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.getDefaultInstance();
      }

      @java.lang.Override
      public com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter build() {
        com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter buildPartial() {
        com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter result = new com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter(this);
        result.counterName_ = counterName_;
        result.prevValue_ = prevValue_;
        result.currentValue_ = currentValue_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter) {
          return mergeFrom((com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter other) {
        if (other == com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter.getDefaultInstance()) return this;
        if (!other.getCounterName().isEmpty()) {
          counterName_ = other.counterName_;
          onChanged();
        }
        if (other.getPrevValue() != 0L) {
          setPrevValue(other.getPrevValue());
        }
        if (other.getCurrentValue() != 0L) {
          setCurrentValue(other.getCurrentValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object counterName_ = "";
      /**
       * <code>string counter_name = 1;</code>
       * @return The counterName.
       */
      public java.lang.String getCounterName() {
        java.lang.Object ref = counterName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          counterName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string counter_name = 1;</code>
       * @return The bytes for counterName.
       */
      public com.google.protobuf.ByteString
          getCounterNameBytes() {
        java.lang.Object ref = counterName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          counterName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string counter_name = 1;</code>
       * @param value The counterName to set.
       * @return This builder for chaining.
       */
      public Builder setCounterName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        counterName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string counter_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCounterName() {
        
        counterName_ = getDefaultInstance().getCounterName();
        onChanged();
        return this;
      }
      /**
       * <code>string counter_name = 1;</code>
       * @param value The bytes for counterName to set.
       * @return This builder for chaining.
       */
      public Builder setCounterNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        counterName_ = value;
        onChanged();
        return this;
      }

      private long prevValue_ ;
      /**
       * <code>int64 prev_value = 2;</code>
       * @return The prevValue.
       */
      @java.lang.Override
      public long getPrevValue() {
        return prevValue_;
      }
      /**
       * <code>int64 prev_value = 2;</code>
       * @param value The prevValue to set.
       * @return This builder for chaining.
       */
      public Builder setPrevValue(long value) {
        
        prevValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 prev_value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrevValue() {
        
        prevValue_ = 0L;
        onChanged();
        return this;
      }

      private long currentValue_ ;
      /**
       * <code>int64 current_value = 3;</code>
       * @return The currentValue.
       */
      @java.lang.Override
      public long getCurrentValue() {
        return currentValue_;
      }
      /**
       * <code>int64 current_value = 3;</code>
       * @param value The currentValue to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentValue(long value) {
        
        currentValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 current_value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentValue() {
        
        currentValue_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Counter)
    }

    // @@protoc_insertion_point(class_scope:Counter)
    private static final com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter();
    }

    public static com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Counter>
        PARSER = new com.google.protobuf.AbstractParser<Counter>() {
      @java.lang.Override
      public Counter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Counter(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Counter> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Counter> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.netapp.asup.serde.common.proto.AggregateOuterClass.Counter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Aggregate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Aggregate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Counter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Counter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017aggregate.proto\"\206\001\n\tAggregate\022\023\n\013objec" +
      "t_name\030\001 \001(\t\022\026\n\016prev_timestamp\030\002 \001(\003\022\031\n\021" +
      "current_timestamp\030\003 \001(\003\022\025\n\rinstance_name" +
      "\030\004 \001(\t\022\032\n\010counters\030\005 \003(\0132\010.Counter\"J\n\007Co" +
      "unter\022\024\n\014counter_name\030\001 \001(\t\022\022\n\nprev_valu" +
      "e\030\002 \001(\003\022\025\n\rcurrent_value\030\003 \001(\003B$\n\"com.ne" +
      "tapp.asup.serde.common.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Aggregate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Aggregate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Aggregate_descriptor,
        new java.lang.String[] { "ObjectName", "PrevTimestamp", "CurrentTimestamp", "InstanceName", "Counters", });
    internal_static_Counter_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Counter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Counter_descriptor,
        new java.lang.String[] { "CounterName", "PrevValue", "CurrentValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
